### ISSUE TITLE
A little help

### ISSUE THREAD

**Issue by theofidry** [xNok/Cssb#1]
https://github.com/in6pio/Incipio/blob/master/gulpfile.babel.js

NB: you should use ES6 now rather than coffeescript ;)

**Comment by xNok** [comment]
thanks, It seems rather complete :) 

 Yes, the new ES6 seems great to write application, but for gulpfile or other small js coffeescript is smarter i find.

**Comment by theofidry** [comment]
Berk, hate CoffeeScript :p, but it's up to you ;) Though there is one thing inconvenient: your require people to know both ES6 and CoffeeScript. That being said, it's not much an issue as the Gulpfile should not change much anyway.
